nitter_redirect: true
nitter_url: "nitter.net"
player: "https://korba.neocities.org/player?url="
show_nsfw: false
thumbnail_large: 300
thumbnail_small: 100
twitter_domains:
  - "x.com"
  - "twitter.com"
  - "fixupx.com"
  - "xfixup.com"
  - "fxtwitter.com"
  - "twittpr.com"
  - "fixvx.com"
  - "vxtwitter.com"
  - "fixvtwitter.com"
  - "stupidpenisx.com"
  - "girlcockx.com"
  - "nitter.net"
  - "xcancel.com"
  - "nitter.poast.org"
  - "nitter.privacyredirect.com"
  - "lightbrd.com"
  - "nitter.space"
  - "nitter.tierkoetter.com"
  - "nuku.trabun.org"
  - "nitter.catsarch.com"
bluesky_domains:
  - "bsky.app"
  - "fxbsky.app"
  - "blacksky.community"
  - "pinksky.app"
  - "azsky.app"
  - "skyview.social/?url=https://bsky.app"
  - "skyview.social/?url=bsky.app"
instagram_domains:
  - "www.instagram.com"
  - "instagram.com"
  - "www.kkinstagram.com"
  - "kkinstagram.com"
  - "www.uuinstagram.com"
  - "uuinstagram.com"
tiktok_domains:
  - "vm.tiktok.com"
reddit_domains:
  - "reddit.com"
  - "www.reddit.com"
  - "old.reddit.com"
  - "new.reddit.com"
  - "rxddit.com"
  - "www.rxddit.com"
  - "old.rxddit.com"
  - "new.rxddit.com"
