nitter_redirect: true
nitter_url: "nitter.net"
player: "https://korba.neocities.org/player?url="
show_nsfw: false
thumbnail_large: 300
thumbnail_small: 100
forum_max_length: 1000
twitter_domains:
  - "x.com"
  - "twitter.com"
  - "fixupx.com"
  - "xfixup.com"
  - "fxtwitter.com"
  - "twittpr.com"
  - "fixvx.com"
  - "vxtwitter.com"
  - "fixvtwitter.com"
  - "stupidpenisx.com"
  - "girlcockx.com"
  - "nitter.net"
  - "xcancel.com"
  - "nitter.poast.org"
  - "nitter.privacyredirect.com"
  - "lightbrd.com"
  - "nitter.space"
  - "nitter.tierkoetter.com"
  - "nuku.trabun.org"
  - "nitter.catsarch.com"
bluesky_domains:
  - "bsky.app"
  - "fxbsky.app"
  - "blacksky.community"
  - "pinksky.app"
  - "azsky.app"
  - "skyview.social/?url=https://bsky.app"
  - "skyview.social/?url=bsky.app"
instagram_domains:
  - "www.instagram.com"
  - "instagram.com"
  - "www.kkinstagram.com"
  - "kkinstagram.com"
  - "www.uuinstagram.com"
  - "uuinstagram.com"
tiktok_domains:
  - "vm.tiktok.com"
reddit_domains:
  - "reddit.com"
  - "www.reddit.com"
  - "old.reddit.com"
  - "new.reddit.com"
  - "rxddit.com"
  - "www.rxddit.com"
  - "old.rxddit.com"
  - "new.rxddit.com"
lemmy_domains:
  - "lemmy.world"
  - "lemmy.ml"
  - "sh.itjust.works"
  - "lemmy.dbzer0.com"
  - "beehaw.org"
  - "lemmy.ca"
  - "programming.dev"
  - "lemmygrad.ml"
  - "lemmygrad.com"
  - "lemmy.blahaj.zone"
  - "ttrpg.network"
  - "lemmy.zip"
  - "lemmy.one"
  - "discuss.tchncs.de"
  - "reddthat.com"
  - "feddit.org"
  - "lemmy.sdf.org"
  - "infosec.pub"
  - "feddit.uk"
  - "lemmings.world"
  - "startrek.website"
  - "feddit.nl"
  - "lemmy.eco.br"
  - "szmer.info"
  - "feddit.it"
  - "discuss.online"
  - "monyet.cc"
  - "lemdro.id"
  - "pawb.social"
  - "jlai.lu"
  - "ani.social"
  - "forum.guncadindex.com"
  - "thelemmy.club"
  - "mander.xyz"
  - "lemmy.wtf"
  - "lemy.lol"
  - "leminal.space"
  - "fosscad.io"
  - "lemmus.org"
  - "lemmy.nz"
  - "literature.cafe"
  - "feddit.dk"
  - "lemmy.org"
  - "lemmy.pt"
  - "r.nf"
  - "chatgptjailbreak.tech"
  - "monero.town"
  - "futurology.today"
  - "lemmy.myserv.one"
  - "feddit.nu"
  - "lemmy.kde.social"
  - "diggita.com"
  - "lemmy.eus"
  - "retrolemmy.com"
  - "lululemmy.com"
  - "lemmy.funami.tech"
  - "eviltoast.org"
  - "scribe.disroot.org"
  - "awful.systems"
  - "europe.pub"
  - "feddit.rocks"
  - "lemmy.radio"
  - "fanaticus.social"
  - "collapse.cat"
  - "lemmy.kya.moe"
  - "hilariouschaos.com"
  - "rblind.com"
  - "lemy.nl"
  - "baraza.africa"
  - "lemmy.ur.mk"
  - "lemmy.dorfrollenspiel.de"
  - "aggregatet.org"
  - "digipres.cafe"
  - "lemmy.fiftyfifty.one"
  - "civilloquy.com"
  - "yall.theatl.social"
  - "lemmy.frozeninferno.xyz"
  - "welppp.com"
  - "crazypeople.online"
  - "bbs.9tail.net"
  - "lemmy.vg"
  - "tucson.social"
  - "group.lt"
